### ISSUE TITLE
Set up the proper database structure

### ISSUE THREAD

**Issue by BGordts** [Job-Protocol/Open-Source-Job-Board#102]
Proposal

partner_role -> used for curation
- user
- role

company -> add these fields for private clients
- is_private
- private_owner: string key (same as password)

role -> 
- is_private
- private_owner: string key (same as password)

**Comment by scheuclu** [comment]
Steps

- [ ] Implement data types
- [ ] Make sure main app does not show private roles
- [ ] Enable curation via partner board

**Comment by scheuclu** [comment]
@BGordts 

I propose to change this in the following way:

- change field private owner to type user
- Authenticate via Bubble like this https://manual.bubble.io/help-guides/working-with-data/authenticating-users#using-your-bubble-app-as-an-sso-provider
